// This file is generated by scripts/sync-frontend.ts.
import type { Address } from "viem";

export const dailyCheckInAddresses: Record<string, Address> = {
  "11155111": "0xbC6b2365187FF74AA84940d0a78f9065fB82E1a1"
};

export function getDailyCheckInAddress(chainId: number | undefined): Address | undefined {
  const configuredAddress = import.meta.env.VITE_DAILY_CHECK_IN_ADDRESS;
  if (configuredAddress && /^0x[a-fA-F0-9]{40}$/.test(configuredAddress)) {
    return configuredAddress as Address;
  }

  return chainId === undefined ? undefined : dailyCheckInAddresses[String(chainId)];
}
