import { existsSync } from "node:fs";
import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import { artifacts } from "hardhat";

type DeploymentAddresses = Record<string, string>;

const rootDirectory = process.cwd();
const generatedDirectory = path.join(rootDirectory, "frontend", "src", "contracts");
const deploymentsDirectory = path.join(rootDirectory, "ignition", "deployments");

function isAddress(value: string | undefined): value is `0x${string}` {
  return value !== undefined && /^0x[a-fA-F0-9]{40}$/.test(value);
}

async function readDeployedAddresses(): Promise<Record<string, `0x${string}`>> {
  const addresses: Record<string, `0x${string}`> = {};

  if (!existsSync(deploymentsDirectory)) {
    return addresses;
  }

  const deploymentDirectories = await readdir(deploymentsDirectory, { withFileTypes: true });

  for (const directory of deploymentDirectories) {
    if (!directory.isDirectory() || !directory.name.startsWith("chain-")) {
      continue;
    }

    const chainId = directory.name.replace("chain-", "");
    const deploymentFile = path.join(
      deploymentsDirectory,
      directory.name,
      "deployed_addresses.json",
    );

    if (!existsSync(deploymentFile)) {
      continue;
    }

    const deployment = JSON.parse(
      await readFile(deploymentFile, "utf8"),
    ) as DeploymentAddresses;
    const dailyCheckInAddress = deployment["DailyCheckInModule#DailyCheckIn"];

    if (isAddress(dailyCheckInAddress)) {
      addresses[chainId] = dailyCheckInAddress;
    }
  }

  const environmentAddress = process.env.DAILY_CHECK_IN_ADDRESS;
  if (isAddress(environmentAddress)) {
    addresses["11155111"] = environmentAddress;
  }

  return addresses;
}

const artifact = await artifacts.readArtifact("DailyCheckIn");
const addresses = await readDeployedAddresses();

await writeFile(
  path.join(generatedDirectory, "dailyCheckInAbi.ts"),
  `// This file is generated by scripts/sync-frontend.ts.\nexport const dailyCheckInAbi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`,
);

await writeFile(
  path.join(generatedDirectory, "addresses.ts"),
  `// This file is generated by scripts/sync-frontend.ts.\nimport type { Address } from "viem";\n\nexport const dailyCheckInAddresses: Record<string, Address> = ${JSON.stringify(addresses, null, 2)};\n\nexport function getDailyCheckInAddress(chainId: number | undefined): Address | undefined {\n  const configuredAddress = import.meta.env.VITE_DAILY_CHECK_IN_ADDRESS;\n  if (configuredAddress && /^0x[a-fA-F0-9]{40}$/.test(configuredAddress)) {\n    return configuredAddress as Address;\n  }\n\n  return chainId === undefined ? undefined : dailyCheckInAddresses[String(chainId)];\n}\n`,
);

console.log(`Synced DailyCheckIn ABI and ${Object.keys(addresses).length} deployed address(es) to frontend.`);
